server:
  port: 8088
spring:
  application:
    name: little-project-rocketmq
  profiles:
    active: dev

dubbo:
  cloud:
    subscribed-services: little-project-redis,little-project-mysql,little-project-message
  scan:
    base-packages: com.ovo.little.project.rocketmq



rocketmq:
  nameserv:
    address: 47.100.222.28:9867 # 当前部署的服务器的外网ip地址 TODO 每次重新部署时修改
  # 登录消息topic
  login:
    topic: login_notify_topic
    producer:
      group: login_notify_producer_group
    consumer:
      group: login_notify_consumer_group
  # 酒店房间数据更新topic
  hotelRoom:
    topic: hotel_room_topic
    producer:
      group: hotel_room_producer_group
    consumer:
      group: hotel_room_consumer_group
  # 订单数据更新topic
  order:
    topic: order_topic
    producer:
      group: order_producer_group
    consumer:
      group: order_consumer_group
first:
  login:
    couponId: 738
    coupon:
      day: 30
